'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { ArrowUpRight,ArrowRight,Check,ChevronRight,ClipboardList,Copy,LayoutDashboard,Link2,LoaderCircle,MapPin,Mic,Package,Plus,RotateCcw,ShieldCheck,ShoppingBag,SlidersHorizontal,Square,Store,Truck,Users,Wallet,X,AlertTriangle,CheckCircle2,Volume2 } from 'lucide-react';
import type { WorkspaceData } from '@/types/workspace';
import type { SupplierQuote } from '@/types';
import { formatPaiseToRupees as money,getFutureDateString } from '@/lib/constants';
import { suggestVoiceFields } from '@/lib/voice-fields';
type Action=Record<string,unknown>;
type View='overview'|'capture'|'orders'|'ledger';
const nav=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'capture',label:'Demand book',icon:ClipboardList},{id:'orders',label:'Shared orders',icon:Package},{id:'ledger',label:'Pickup ledger',icon:Wallet}] as const;
const date=(value:string)=>new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',timeZone:'Asia/Kolkata'});
const stamp=(value:string)=>new Date(value).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit',timeZone:'Asia/Kolkata'});
function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'good'|'warn'|'neutral'}){return <span className={`badge ${tone}`}>{children}</span>;}
function Brand(){return <span className="brand"><span className="brand-mark"><ShoppingBag size={23}/><span/></span>Nahi<span>Mila</span></span>;}
function ProductArt({small=false}:{small?:boolean}){return <div className={`product-art ${small?'small':''}`} aria-label="Fictional Millet Crunch packet"><div className="packet"><span className="packet-brand">MILLET<br/>CRUNCH</span><span className="packet-grain">✳</span><span className="packet-flavour">MASALA</span><span className="packet-weight">100g · snack happy</span></div>{!small&&<><span className="art-orbit o1"/><span className="art-orbit o2"/><span className="art-caption">Small requests.<br/>Shared possibilities.</span></>}</div>;}
export default function Workspace({customerToken}:{customerToken?:string}){
 const [workspace,setWorkspace]=useState('');const [data,setData]=useState<WorkspaceData|null>(null);const [view,setView]=useState<View>('overview');
 const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [guide,setGuide]=useState(false);const [reset,setReset]=useState(false);const [offerToken,setOfferToken]=useState(customerToken||'REQ-NML-8808');
 const [editQuote,setEditQuote]=useState<SupplierQuote|null>(null);const [selectedQuote,setSelectedQuote]=useState('quote-b');
 useEffect(()=>{
 // Hydrate the browser workspace identity after mount; it is shared through offer links.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 const url=new URL(window.location.href);let id=url.searchParams.get('workspace');if(!id){id=window.localStorage.getItem('nahimila-workspace')||crypto.randomUUID();url.searchParams.set('workspace',id);window.history.replaceState(null,'',url);}window.localStorage.setItem('nahimila-workspace',id);setWorkspace(id);},[]);
 const refresh=useCallback(async()=>{if(!workspace)return;try{const r=await fetch(`/api/workspace?workspace=${workspace}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);}catch(e){setError(e instanceof Error?e.message:'Unable to load workspace.');}},[workspace]);
 useEffect(()=>{const initial=setTimeout(refresh,0);const timer=setInterval(refresh,3000);return()=>{clearTimeout(initial);clearInterval(timer);};},[refresh]);
 const navigate=(next:View)=>{setView(next);window.scrollTo({top:0});};
 const act=async(action:Action)=>{if(busy)return false;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...action,workspace})});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j.data);setNotice(j.message);if(j.token)setOfferToken(j.token);return true;}catch(e){setError(e instanceof Error?e.message:'Unable to save changes.');return false;}finally{setBusy(false);}};
 const offerUrl=(token:string)=>`${typeof window!=='undefined'?window.location.origin:''}/confirm/${token}?workspace=${workspace}`;
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);setNotice('Link copied. Open it on another device connected to this server.');}catch{setError('Clipboard is unavailable. Copy the address from the opened customer page.');}};
 const closeGuide=useCallback(()=>setGuide(false),[]),closeReset=useCallback(()=>setReset(false),[]),closeQuote=useCallback(()=>setEditQuote(null),[]);
 if(!data)return <div className="loading-page"><Brand/>{error?<><p role="alert">{error}</p><button className="btn" onClick={refresh}>Try again</button></>:<><LoaderCircle className="spin"/><p>Opening your neighbourhood workspace…</p></>}</div>;
 const active=data.reservations.filter(r=>r.status==='ACTIVE');const count=active.filter(r=>r.sku==='MC-MASALA-100G').reduce((s,r)=>s+r.quantity,0);
 const order=data.orders[0];const quote=order?.supplier_quote||data.quotes.find(q=>q.id===selectedQuote)||data.quotes[1];const evaluation=order?.evaluation||data.evaluations.find(e=>e.quote_id===quote.id)!;
 const displayCount=order?.total_units??count;
 const reservedReceipts=data.reservations.filter(r=>r.status!=='CANCELLED').reduce((s,r)=>s+r.quantity*r.confirmed_price_paise,0);
 const baselineExposure=data.evaluations.find(e=>e.quote_id==='quote-b')?.allocations[0]?.total_exposure_paise;
 const approvals=evaluation.allocations.filter(a=>a.approval_status==='APPROVED').length;
 const reservedValue=active.reduce((s,r)=>s+r.quantity*r.confirmed_price_paise,0);
 const confirmed=!!data.reservations.find(r=>r.request_token===offerToken&&(r.status==='ACTIVE'||r.status==='COMMITTED'||r.status==='FULFILLED'));
 const offerRequest=data.requests.find(r=>r.request_token===offerToken);const offer=data.offers.find(o=>o.request_token===offerToken);
 const merchant=data.merchants.find(m=>m.id===offerRequest?.merchant_id);const product=data.products.find(p=>p.id===offerRequest?.product_id);
 const pending=data.requests.filter(r=>r.status==='OFFER_CREATED');
 const flash=<>{error&&<div className="flash error" role="alert"><AlertTriangle size={18}/><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="flash success" role="status"><CheckCircle2 size={18}/><span>{notice}</span><button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={16}/></button></div>}</>;
 const customerCard=<div className="customer-card"><div className="customer-card-head"><Badge tone={confirmed?'good':'warn'}>{offerRequest&&['NO_SHOW','PICKED_UP'].includes(offerRequest.status)?'Pickup outcome recorded':confirmed?'Reservation confirmed':'Your local shop has an offer'}</Badge><ProductArt small/></div>{offerRequest&&offer&&product?<><p className="eyebrow">EXACT PRODUCT. YOUR LOCAL SHOP.</p><h2>{product.name}</h2><p className="muted">{product.pack_size} pack · {offerRequest.quantity} {offerRequest.quantity===1?'unit':'units'}</p><dl className="offer-details"><div><dt>Price per unit</dt><dd>{money(offer.proposed_price_paise)}</dd></div><div><dt>Pick up from</dt><dd>{merchant?.name}</dd></div><div><dt>Pick up by</dt><dd>{stamp(offer.pickup_deadline)}</dd></div></dl><div className="info-note"><ShieldCheck size={20}/><span>This is a conditional reservation. Your shop will order only if enough customers confirm and each shop agrees. No payment or guaranteed supply.</span></div>{['PICKED_UP','NO_SHOW'].includes(offerRequest.status)?<Badge>{offerRequest.status==='PICKED_UP'?'Pickup recorded':'No-show recorded'}</Badge>:confirmed?<><div className="confirmed-message"><CheckCircle2/>Counted once. Thank you!</div><button className="btn secondary full" disabled={busy||offerRequest.status==='READY_FOR_PICKUP'} onClick={()=>act({action:'cancel',token:offerToken})}>Withdraw reservation</button>{offerRequest.status==='READY_FOR_PICKUP'&&<p className="fine">Demo supplier commitment recorded. Customer cancellation cannot undo that cost.</p>}</>:<button className="btn full" disabled={busy} onClick={()=>act({action:'confirm',token:offerToken})}>{busy?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>}Confirm this exact offer</button>}<p className="fine center">Repeated confirmation never adds another reservation.</p></>:<div className="empty"><AlertTriangle/><h3>Offer not found</h3><p>Use the complete link from your shop, including its workspace.</p></div>}</div>;
 if(customerToken)return <div className="customer-page"><header><a href={`/?workspace=${workspace}`}><Brand/></a><Badge>Customer view · demo</Badge></header><main>{flash}{customerCard}<p className="customer-footer">A little patience. A new possibility for your neighbourhood shop.</p><p className="fine center">Fictional products and offers. No real order or payment.</p></main></div>;
 return <div className="app-shell">
 <aside className="sidebar"><a className="brand-link" href={`/?workspace=${workspace}`}><Brand/></a><div className="workspace-label">MERCHANT WORKSPACE</div><nav aria-label="Main navigation">{nav.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>navigate(n.id)}><n.icon size={19}/>{n.label}{n.id==='capture'&&<span>{data.requests.length}</span>}{n.id==='orders'&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="community-mini"><div className="avatars"><span>SK</span><span>GG</span><span>LP</span></div><b>Stronger, together.</b><p>3 neighbourhood shops<br/>One shared opportunity.</p></div><button onClick={()=>setGuide(true)}><Volume2 size={18}/>Demo walkthrough<ArrowUpRight size={15}/></button><div className="profile"><span>RS</span><div><b>Neighbourhood demo</b><small>Indiranagar · Bengaluru</small></div></div></div></aside>
 <div className="main-shell"><header className="topbar"><div className="mobile-brand"><Brand/></div><div className="breadcrumb">Workspace <ChevronRight size={14}/><span>{nav.find(n=>n.id===view)?.label}</span></div><div className="top-actions"><span className="live-label"><i/>Demo workspace</span><button className="icon-btn" title="Reset demo" aria-label="Reset demo" onClick={()=>setReset(true)}><RotateCcw size={18}/></button><button className="btn small" onClick={()=>navigate('capture')}><Plus size={16}/>New request</button></div></header>
 <nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(n=><button className={view===n.id?'active':''} key={n.id} onClick={()=>navigate(n.id)}><n.icon size={17}/>{n.label}</button>)}</nav>
 <main className="content">{flash}
 {view==='overview'&&<>
 <div className="page-heading"><div><p className="eyebrow">YOUR NEIGHBOURHOOD, CONNECTED</p><h1>A “nahi mila” can<br className="mobile-break"/> become your next sale.</h1><p>Capture what customers ask for. Order together when the numbers work.</p></div><button className="text-btn" onClick={()=>setGuide(true)}>How it works<ArrowUpRight size={16}/></button></div>
 <section className="hero-card"><div className="hero-copy"><Badge>SHARED DEMAND · MASALA 100g</Badge><h2>{order?'From missed demand\nto a shared order.':count>=24?'The case is covered.\nNow check the numbers.':'One more “yes”.\nA whole new possibility.'}</h2><p>{order?'Your shops committed together. Track collections to see what became cash and what remains on the shelf.':`${count} confirmed units across ${new Set(active.map(r=>r.merchant_id)).size} shops. A 24-unit supplier case, backed by customers rather than guesswork.`}</p><div className="hero-actions"><button className="btn light" onClick={()=>navigate(order?'ledger':'orders')}>{order?'Track pickups':'Explore shared order'}<ArrowRight size={17}/></button>{!order&&count<24&&<a className="hero-link" href={offerUrl('REQ-NML-8808')} target="_blank" rel="noreferrer">Open customer offer<ArrowUpRight size={16}/></a>}</div><div className="hero-foot"><ShieldCheck size={15}/>No speculative extras. Every shop controls its cash.</div></div><ProductArt/></section>
 <div className="stats-grid"><Stat label="Confirmed demand" value={order?`${order.total_units}`:String(count)} note="Exact Masala 100g units" icon={<Users/>}/><Stat label="Reserved sales value" value={order?money(reservedReceipts):money(reservedValue)} note="Potential receipts, not earned revenue" icon={<ShoppingBag/>}/><Stat label="Cash needed per shop" value={order?money(order.merchant_allocations[0].exposure_paise):count===24&&baselineExposure?money(baselineExposure):'—'} note={order?'Committed supplier cost':'Shown when the case is fully covered'} icon={<Wallet/>}/><Stat label="Unsupported extras" value="0" note="We never assume customers for spare stock" icon={<ShieldCheck/>}/></div>
 <div className="overview-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">NEIGHBOURHOOD DEMAND</p><h2>Small shops. One supplier case.</h2></div><Badge>{displayCount} / 24 units</Badge></div><div className="case-progress" aria-label={`${displayCount} of 24 units reserved`}>{Array.from({length:24},(_,i)=><span key={i} className={i<displayCount?'filled':''}/>)}</div><div className="progress-label"><span>{Math.max(0,24-displayCount)} more to cover this case</span><b>No inventory sync needed</b></div><div className="shop-list">{data.merchants.map((m,i)=>{const qty=active.filter(r=>r.merchant_id===m.id&&r.sku==='MC-MASALA-100G').reduce((s,r)=>s+r.quantity,0);return <div key={m.id}><span className={`shop-icon c${i}`}><Store size={21}/></span><div><b>{m.name}</b><small>{m.neighborhood}</small></div><span><b>{order?order.merchant_allocations.find(a=>a.merchant_id===m.id)?.units||0:qty}</b> units</span></div>;})}</div><button className="text-btn full" onClick={()=>navigate('orders')}>Review supplier options<ArrowRight size={16}/></button></section>
 <section className="panel steps-panel"><p className="eyebrow">THE BETTER WAY TO SAY “NOT AVAILABLE”</p><h2>A request, not a dead end.</h2>{[{title:'Capture the exact request',text:'Product, pack, price and when the customer can return.',icon:ClipboardList},{title:'Let customers confirm',text:'A clear, conditional offer. Only a “yes” counts.',icon:Users},{title:'Order only when it works',text:'Whole cases, delivery, cash caps and every shop’s approval.',icon:ShieldCheck}].map((s,i)=><div className="step" key={s.title}><span><s.icon size={20}/></span><div><small>0{i+1}</small><h3>{s.title}</h3><p>{s.text}</p></div></div>)}</section></div>
 <div className="quiet-banner"><MapPin size={17}/><p>Built for customers who can wait for a specific product. Urgent purchases stay outside this flow.</p><Badge>Synthetic scenario</Badge></div>
 </>}
 {view==='capture'&&<><div className="page-heading"><div><p className="eyebrow">TURN A MISSED REQUEST INTO DEMAND</p><h1>Your demand book.</h1><p>Give the customer an exact offer. Their confirmation makes it count.</p></div><Badge>{pending.length} awaiting confirmation</Badge></div><div className="capture-grid"><CaptureForm data={data} busy={busy} act={act}/><section className="panel offer-preview"><div className="panel-heading"><div><p className="eyebrow">WHAT THE CUSTOMER SEES</p><h2>A promise with clear terms.</h2></div><Link2 size={20}/></div>{customerCard}<div className="offer-link-actions"><button className="btn secondary" onClick={()=>copy(offerUrl(offerToken))}><Copy size={16}/>Copy offer link</button><a className="btn secondary" href={offerUrl(offerToken)} target="_blank" rel="noreferrer">Open offer<ArrowUpRight size={16}/></a></div></section></div><section className="panel demand-table"><div className="panel-heading"><h2>Requests, with a next step.</h2><Badge>{data.requests.length} requests</Badge></div><div className="table-scroll"><table><thead><tr><th>Customer / shop</th><th>Exact request</th><th>Offer</th><th>Pickup by</th><th>Status</th><th/></tr></thead><tbody>{[...data.requests].reverse().map(r=>{const p=data.products.find(p=>p.id===r.product_id);return <tr key={r.id}><td><b>{r.customer_name}</b><small>{data.merchants.find(m=>m.id===r.merchant_id)?.name}</small></td><td>{p?.name}<small>{r.pack_size} · {r.quantity} unit</small></td><td>{money(r.max_retail_price_paise)}</td><td>{date(r.required_by_date)}</td><td><Badge tone={r.status==='CUSTOMER_CONFIRMED'?'good':r.status==='OFFER_CREATED'?'warn':'neutral'}>{statusLabel(r.status)}</Badge></td><td><button className="text-btn" onClick={()=>{setOfferToken(r.request_token);window.scrollTo({top:0,behavior:'smooth'});}}>View offer<ArrowUpRight size={14}/></button></td></tr>;})}</tbody></table></div></section></>}
 {view==='orders'&&<><div className="page-heading"><div><p className="eyebrow">CUSTOMER-BACKED PROCUREMENT</p><h1>One case. Three cash decisions.</h1><p>The lowest unit price is only useful when the entire order works.</p></div><Badge tone={order?'good':count===24?'good':'warn'}>{order?'Demo order committed':`${count} confirmed units`}</Badge></div>
 <div className="order-product"><ProductArt small/><div><p className="eyebrow">SHARED CASE</p><h2>Millet Crunch · Masala</h2><p>Exact SKU MC-MASALA-100G · 100g · {displayCount} {order?'committed':'active reserved'} units</p></div><div className="order-product-note"><ShieldCheck size={18}/><span>Supplier cases require<br/><b>fully backed units.</b></span></div></div>
 <div className="section-title"><h2>{order?'Committed supplier terms':'Compare supplier quotes'}</h2><span>Manual quote input · fictional suppliers</span></div><div className="quote-grid">{(order?[quote]:data.quotes).map(q=>{const ev=order?evaluation:data.evaluations.find(e=>e.quote_id===q.id)!;return <button key={q.id} className={`quote-card ${order||selectedQuote===q.id?'selected':''}`} onClick={()=>setSelectedQuote(q.id)}><div className="quote-top"><span className="supplier-icon"><Truck size={19}/></span><span>QUOTE {String.fromCharCode(65+data.quotes.findIndex(item=>item.id===q.id))} · v{q.version}</span><span className="radio-dot"/></div><h3>{q.supplier_name}</h3><div className="quote-price">{money(q.unit_cost_paise)}<span>/ unit</span></div><div className="quote-facts"><span>Case size <b>{q.moq} units</b></span><span>Logistics <b>{money(q.transport_cost_paise+q.handling_cost_paise)}</b></span><span>Delivery <b>{date(q.expected_delivery_date)}</b></span></div><Badge tone={ev.is_eligible?'good':'warn'}>{order?'Committed · simulated':ev.is_eligible?'Eligible for shop approval':!ev.moq_met?'Case not fully covered':!ev.arrives_in_time?'Arrives too late':!ev.all_merchants_within_cap?'Cash limit exceeded':'Needs review'}</Badge></button>;})}</div>
 <div className="orders-detail-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">{order?'CHECKS AT COMMITMENT · SAVED SNAPSHOT':'WHY THIS QUOTE'} {!order&&(evaluation.is_eligible?'WORKS':'IS BLOCKED')}</p><h2>Every constraint, checked.</h2></div><button className="btn secondary small" disabled={!!order} onClick={()=>setEditQuote(quote)}><SlidersHorizontal size={15}/>Edit quote</button></div><div className="rule-list">{evaluation.rule_checks.map(c=><div key={c.rule}><span className={c.passed?'rule-pass':'rule-fail'}>{c.passed?<Check size={15}/>:<X size={15}/>}</span><div><b>{c.rule}</b><p>{c.message}</p></div></div>)}</div></section><section className="panel exposure-panel"><p className="eyebrow">LANDED CASH EXPOSURE</p><h2>{money(evaluation.total_procurement_cost_paise)}<span> / shared order</span></h2><p>Goods, transport and handling. Split by reserved units, down to the paise.</p><dl><div><dt>Goods</dt><dd>{money(evaluation.total_demand_units*quote.unit_cost_paise)}</dd></div><div><dt>Transport + handling</dt><dd>{money(quote.transport_cost_paise+quote.handling_cost_paise)}</dd></div><div><dt>Potential customer receipts</dt><dd>{money((order?data.reservations.filter(r=>r.status!=='CANCELLED'):active).filter(r=>r.sku===quote.sku&&r.pack_size===quote.pack_size).reduce((s,r)=>s+r.quantity*r.confirmed_price_paise,0))}</dd></div><div><dt>Projected contribution before overhead</dt><dd>{money((order?data.reservations.filter(r=>r.status!=='CANCELLED'):active).filter(r=>r.sku===quote.sku&&r.pack_size===quote.pack_size).reduce((s,r)=>s+r.quantity*r.confirmed_price_paise,0)-evaluation.total_procurement_cost_paise)}</dd></div></dl><div className="info-note"><Wallet size={20}/><span>Reservations are not payments. Each shop still carries its supplier cost if customers don’t collect.</span></div></section></div>
 <section className="panel"><div className="panel-heading"><div><p className="eyebrow">EACH SHOP HAS THE FINAL SAY</p><h2>Review cash. Approve your share.</h2></div><Badge>{approvals} / {evaluation.allocations.length} approved</Badge></div><div className="allocation-grid">{evaluation.allocations.map((a,i)=><div className="allocation-card" key={a.merchant_id}><div className="allocation-title"><span className={`shop-icon c${i}`}><Store size={19}/></span><h3>{a.merchant_name}</h3></div><div className="exposure-number">{money(a.total_exposure_paise)}<span>{a.allocated_units} units · including logistics</span></div><CapInput key={`${a.merchant_id}-${a.cash_cap_paise}`} value={a.cash_cap_paise} disabled={busy||!!order} save={n=>act({action:'cap',merchant_id:a.merchant_id,cap_paise:n})}/><label className="permission"><input type="checkbox" disabled={busy||!!order} checked={data.merchants.find(m=>m.id===a.merchant_id)!.allowed_suppliers.includes(quote.supplier_id)} onChange={e=>act({action:'permission',merchant_id:a.merchant_id,supplier_id:quote.supplier_id,allowed:e.target.checked})}/>Permit this supplier</label><p className={a.within_cap?'headroom':'shortfall'}>{a.within_cap?`${money(a.cash_cap_headroom_paise)} within your limit`:`${money(-a.cash_cap_headroom_paise)} over your limit`}</p>{a.approval_status==='INVALIDATED'&&<p className="fine warning">Previous approval cleared. Review again.</p>}<button className={`btn full ${a.approval_status==='APPROVED'?'secondary':''}`} disabled={busy||!!order||!evaluation.is_eligible||a.approval_status==='APPROVED'} onClick={()=>act({action:'approve',merchant_id:a.merchant_id,quote_id:quote.id,quote_version:quote.version,exposure_paise:a.total_exposure_paise})}><Check size={17}/>{a.approval_status==='APPROVED'?'Share approved':'Approve this cash exposure'}</button></div>)}</div><div className="commit-bar"><div><b>{order?'Supplier commitment simulated.':evaluation.is_eligible?'Ready when all shops agree.':'The order stays blocked.'}</b><p>{order?'Committed cost is retained in the pickup ledger.':'A final server check runs again before an order is recorded.'}</p></div>{order?<button className="btn" onClick={()=>navigate('ledger')}>Open pickup ledger<ArrowRight size={17}/></button>:<button className="btn" disabled={busy||!evaluation.is_eligible||approvals!==evaluation.allocations.length} onClick={()=>act({action:'commit',quote_id:quote.id})}>Simulate supplier commitment<ArrowRight size={17}/></button>}</div></section></>}
 {view==='ledger'&&<><div className="page-heading"><div><p className="eyebrow">FROM CONFIRMATION TO COLLECTION</p><h1>Reservations aren’t revenue.</h1><p>See the cash received, inventory remaining and supplier cost still committed.</p></div><Badge>Simulated pickup outcomes</Badge></div>{!order?<section className="panel empty"><Package size={42}/><h2>First, commit a shared order.</h2><p>Pickup accounting starts with actual committed demo cost. We don’t invent receipts.</p><button className="btn" onClick={()=>navigate('orders')}>Review shared orders<ArrowRight size={17}/></button></section>:<><div className="ledger-grid">{data.analyses.map((a,i)=><section className="panel ledger-card" key={a.merchant_id}><span className={`shop-icon c${i}`}><Store size={20}/></span><h3>{a.merchant_name}</h3><div className="ledger-main">{money(a.collected_cash_paise)}<span>customer cash collected</span></div><dl><div><dt>Committed supplier cost</dt><dd>{money(a.total_procurement_cost_paise)}</dd></div><div><dt>Units collected</dt><dd>{a.collected_units} / {a.allocated_units}</dd></div><div><dt>Units still on shelf</dt><dd>{a.uncollected_units}</dd></div><div className="ledger-shortfall"><dt>Current cash shortfall</dt><dd>{money(a.current_cash_shortfall_paise)}</dd></div></dl><p className="fine">Unsold units remain inventory. A cash shortfall is not automatically an accounting loss.</p></section>)}</div><section className="panel"><div className="panel-heading"><h2>Record each customer’s outcome</h2><Badge>{data.pickups.length} / {order.total_units} recorded</Badge></div><div className="table-scroll"><table><thead><tr><th>Customer / shop</th><th>Reservation</th><th>Potential cash</th><th>Outcome</th></tr></thead><tbody>{data.reservations.filter(r=>['COMMITTED','FULFILLED','NO_SHOW'].includes(r.status)).map(r=>{const req=data.requests.find(q=>q.id===r.request_id);const pickup=data.pickups.find(p=>p.reservation_id===r.id);return <tr key={r.id}><td><b>{req?.customer_name}</b><small>{data.merchants.find(m=>m.id===r.merchant_id)?.name}</small></td><td>{r.quantity} × Masala 100g</td><td>{money(r.quantity*r.confirmed_price_paise)}</td><td>{pickup?<Badge tone={pickup.outcome==='COLLECTED'?'good':'warn'}>{pickup.outcome==='COLLECTED'?'Collected':'No-show'}</Badge>:<div className="outcome-actions"><button className="btn secondary small" disabled={busy} onClick={()=>act({action:'pickup',reservation_id:r.id,outcome:'COLLECTED'})}><Check size={14}/>Collected</button><button className="text-btn" disabled={busy} onClick={()=>act({action:'pickup',reservation_id:r.id,outcome:'NO_SHOW'})}>No-show</button></div>}</td></tr>;})}</tbody></table></div></section></>}</>}
 <footer className="workspace-footer"><span><i/>{data.storageMode} · updates across views</span><span>Fictional products & quotes. No real payments or supplier orders.</span></footer>
 </main></div>
 {guide&&<Modal title="A demo that you can challenge." close={closeGuide}><p className="muted">Use real inputs and separate customer pages. Every result recomputes on the server.</p><ol className="guide-list"><li><b>Start at 23 reservations.</b> Open Customer 08’s offer from the demand book. Confirm in a second tab: the case reaches 24. Confirm again to check it stays 24.</li><li><b>Compare all three quotes.</b> A is cheap but needs 48 units. B costs ₹344 per shop. C is cheaper but arrives late.</li><li><b>Challenge the cash decision.</b> Set one shop’s cash limit to ₹330. B blocks. Edit C’s delivery to tomorrow: ₹328 per shop now fits.</li><li><b>Test a cancellation.</b> Withdraw a customer reservation before commitment. Demand drops to 23 and all approvals clear. Reconfirm for a new approval round.</li><li><b>Finish with the real outcome.</b> Commit B at a ₹350 cap, record six collections and two no-shows at one shop: ₹300 cash, ₹344 cost, ₹44 shortfall and two unsold units.</li></ol><div className="info-note"><ShieldCheck size={20}/><span>Supplier quotes, acceptance, delivery and pickups are synthetic. Sarvam voice is live only when configured. No merchant impact claim has been validated yet.</span></div><button className="btn full" onClick={()=>{setGuide(false);navigate('capture');setOfferToken('REQ-NML-8808');}}>Start with the customer offer<ArrowRight size={17}/></button></Modal>}
 {reset&&<Modal title="Start a fresh demonstration?" close={closeReset}><p>This resets this workspace to 23 active reservations and one pending offer. It clears its quotes, approvals, simulated order and pickup records.</p><div className="modal-actions"><button className="btn secondary" onClick={()=>setReset(false)}>Keep my changes</button><button className="btn" disabled={busy} onClick={async()=>{if(await act({action:'reset'})){setReset(false);navigate('overview');setOfferToken('REQ-NML-8808');}}}>Reset this demo</button></div></Modal>}
 {editQuote&&<QuoteEditor quote={editQuote} busy={busy} save={async a=>{if(await act(a))setEditQuote(null);}} close={closeQuote}/>}
 </div>;
}
function statusLabel(status:string){return ({OFFER_CREATED:'Awaiting customer',CUSTOMER_CONFIRMED:'Confirmed',CANCELLED:'Withdrawn',READY_FOR_PICKUP:'Demo committed',PICKED_UP:'Collected',NO_SHOW:'No-show'} as Record<string,string>)[status]||status;}
function Stat({label,value,note,icon}:{label:string;value:string;note:string;icon:React.ReactNode}){return <section className="stat-card"><div><span>{label}</span>{icon}</div><b>{value}</b><p>{note}</p></section>;}
function Modal({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const before=document.activeElement as HTMLElement;ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=ref.current?.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old;before?.focus();};},[close]);return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)close();}}><div className="modal" ref={ref} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}><div className="panel-heading"><h2>{title}</h2><button className="icon-btn" aria-label="Close dialog" onClick={close}><X size={20}/></button></div>{children}</div></div>;}
function CapInput({value,disabled,save}:{value:number;disabled:boolean;save:(n:number)=>void}){const [draft,setDraft]=useState(String(value/100));return <div className="cap-field"><label>My cash limit <span>₹</span><input aria-label="Cash limit in rupees" type="number" min="0" step="0.01" disabled={disabled} value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="text-btn" disabled={disabled||draft===''||Math.round(Number(draft)*100)===value} onClick={()=>save(Math.round(Number(draft)*100))}>Save</button></div>;}
function QuoteEditor({quote:q,busy,save,close}:{quote:SupplierQuote;busy:boolean;save:(a:Action)=>void;close:()=>void}){const local=(s:string)=>{const d=new Date(s);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};return <Modal title={`Edit ${q.supplier_name}`} close={close}><p className="muted">Enter supplier terms manually. Changing any term clears previous approvals.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({action:'quote',quote_id:q.id,sku:f.get('sku'),pack_size:f.get('pack'),unit_paise:Math.round(Number(f.get('unit'))*100),moq:Number(f.get('moq')),transport_paise:Math.round(Number(f.get('transport'))*100),handling_paise:Math.round(Number(f.get('handling'))*100),delivery:new Date(String(f.get('delivery'))).toISOString(),expiry:new Date(String(f.get('expiry'))).toISOString()});}}><div className="form-grid"><label>Exact SKU<input name="sku" defaultValue={q.sku} required/></label><label>Pack size<input name="pack" defaultValue={q.pack_size} required/></label><label>Unit cost (₹)<input name="unit" type="number" min="0.01" step="0.01" defaultValue={q.unit_cost_paise/100} required/></label><label>Units per supplier case<input name="moq" type="number" min="1" step="1" defaultValue={q.moq} required/></label><label>Transport (₹)<input name="transport" type="number" min="0" step="0.01" defaultValue={q.transport_cost_paise/100} required/></label><label>Handling (₹)<input name="handling" type="number" min="0" step="0.01" defaultValue={q.handling_cost_paise/100} required/></label><label>Expected delivery · your local time<input name="delivery" type="datetime-local" defaultValue={local(q.expected_delivery_date)} required/></label><label>Quote expiry · your local time<input name="expiry" type="datetime-local" defaultValue={local(q.quote_expiry_date)} required/></label></div><button className="btn full" disabled={busy}>Save terms & recheck order<ArrowRight size={17}/></button></form></Modal>;}
function CaptureForm({data,busy,act}:{data:WorkspaceData;busy:boolean;act:(a:Action)=>Promise<boolean>}){
 const [product,setProduct]=useState('prod-millet');const [quantity,setQuantity]=useState('1');const [price,setPrice]=useState('50');const [deadline,setDeadline]=useState(getFutureDateString(2));const [wait,setWait]=useState(false);const [transcript,setTranscript]=useState('');const [voiceError,setVoiceError]=useState('');const [recording,setRecording]=useState(false);const [transcribing,setTranscribing]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());},[]);
 const record=async()=>{setVoiceError('');if(recording){recorder.current?.stop();return;}try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone requires localhost or HTTPS. Use typed entry here.');stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream.current);recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=async()=>{setRecording(false);if(timer.current)clearTimeout(timer.current);stream.current?.getTracks().forEach(t=>t.stop());setTranscribing(true);try{const f=new FormData();f.append('file',new Blob(chunks,{type:r.mimeType}),r.mimeType.includes('mp4')?'request.m4a':'request.webm');const response=await fetch('/api/voice/transcribe',{method:'POST',body:f});const j=await response.json();if(!response.ok)throw new Error(j.error);setTranscript(j.transcript);const fields=suggestVoiceFields(j.transcript);setProduct(fields.productId||'');setQuantity(fields.quantity?String(fields.quantity):'');setPrice(fields.price?String(fields.price):'');setDeadline(fields.deadline||'');}catch(e){setVoiceError(e instanceof Error?e.message:'Transcription unavailable. Please type the request.');}finally{setTranscribing(false);}};r.start();setRecording(true);timer.current=setTimeout(()=>{if(r.state==='recording')r.stop();},20000);}catch(e){stream.current?.getTracks().forEach(t=>t.stop());setVoiceError(e instanceof Error?e.message:'Microphone unavailable.');}};
 const p=data.products.find(p=>p.id===product);
 return <section className="panel capture-form"><div className="panel-heading"><div><p className="eyebrow">A CUSTOMER ASKED FOR…</p><h2>Remember the sale you couldn’t make.</h2></div><ClipboardList size={21}/></div><div className="voice-entry"><div><Mic size={22}/><div><b>Say it in your own language.</b><p>{data.voiceAvailable?'Sarvam transcription · review before saving':'Sarvam key not configured · typed entry is ready'}</p></div></div><button type="button" className={`btn secondary small ${recording?'recording':''}`} disabled={!data.voiceAvailable||transcribing||busy} onClick={record}>{transcribing?<LoaderCircle className="spin" size={16}/>:recording?<Square size={14}/>:<Mic size={16}/>} {recording?'Stop':transcribing?'Transcribing':'Record · 20s'}</button></div>{voiceError&&<p className="inline-error" role="alert">{voiceError}</p>}{transcript&&<label className="transcript-field">Review your Sarvam transcript<textarea value={transcript} onChange={e=>setTranscript(e.target.value)}/><small>Only explicit matches are suggested below. Review every field; unclear values stay blank.</small></label>}
 <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await act({action:'create',merchant_id:f.get('merchant'),product_id:product,quantity:Number(quantity),price_paise:Math.round(Number(price)*100),deadline,can_wait:wait,reason:f.get('reason'),customer_name:f.get('customer')});}}><div className="form-grid"><label className="span-2">Shop<select name="merchant">{data.merchants.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label className="span-2">Exact product & variant<select value={product} required onChange={e=>{setProduct(e.target.value);setPrice(String(data.products.find(p=>p.id===e.target.value)!.standard_mrp_paise/100));}}><option value="" disabled>Select the exact product and pack</option>{data.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.pack_size}</option>)}</select><small>{p?`${p.sku} · exact pack: ${p.pack_size}`:'Unrecognised product — choose it explicitly.'}</small></label><label>Quantity<input type="number" min="1" max="100" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label>Customer budget / unit (₹)<input type="number" min="0.01" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label>Pick up by · 8pm IST<input type="date" min={getFutureDateString(0)} value={deadline} onChange={e=>setDeadline(e.target.value)} required/></label><label>Why unavailable?<select name="reason"><option value="not_stocked">Shop doesn’t stock it</option><option value="out_of_stock">Temporarily out of stock</option><option value="wrong_variant">Different variant</option><option value="wrong_pack">Different pack size</option><option value="price_mismatch">Outside customer budget</option></select></label><label className="span-2">Customer name / nickname<input name="customer" placeholder="e.g. Asha" maxLength={80} required autoComplete="off"/></label></div><label className="wait-check"><input type="checkbox" checked={wait} onChange={e=>setWait(e.target.checked)}/><span><b>The customer can wait until this deadline.</b><small>This flow doesn’t promise instant fulfilment.</small></span></label><button className="btn full" disabled={busy||!wait}>{busy?<LoaderCircle className="spin" size={18}/>:<Plus size={18}/>}Create customer confirmation link</button><p className="fine center">Saving a request adds zero confirmed demand until the customer says yes.</p></form></section>;
}
